import 'SegnalazioneClass.dart';
List<Segnalazione> segnala = [
  Segnalazione(
    id: "1",
    titolo: "Titolo Segnalazione",
    data: "21/02/2020",
    stato: "Attesa",
    sostegno: 0 ,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniamquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: "assets/images/icona_animale_vagante.png",
    image1: "assets/images/cane.jpg",
    image2: "assets/images/icona_noPhoto.png",
    mappa:"assets/images/mappaPordenone.png",
    indirizzo:"Via Prasecco, 3/a Pordenone",
  ),
  Segnalazione(
    id: "2",
    titolo: "Titolo Segnalazione",
    data: "19/02/2020",
    stato: "Attesa",
    sostegno: 1 ,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniamquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: "assets/images/icona_animali_selvaggi.png",
    image1: "assets/images/lepre.jpg",
    image2: "assets/images/icona_noPhoto.png",
    mappa:"assets/images/mappaPordenone.png",
    indirizzo:"Via Prasecco, 3/a Pordenone",
  ),
 Segnalazione(
    id: "3",
    titolo: "Titolo Segnalazione",
    data: "15/02/2020",
    stato: "Attesa",
    sostegno: 3 ,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniamquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: "assets/images/icona_spazzatura.png",
   image1: "assets/images/spazzatura.jpg",
   image2: "assets/images/icona_noPhoto.png",
    mappa:"assets/images/mappaPordenone.png",
    indirizzo:"Via Prasecco, 3/a Pordenone",
  ),
 Segnalazione(
    id: "4",
    titolo: "Titolo Segnalazione",
    data: "10/02/2020",
   stato: "Attesa",
   sostegno: 2 ,
   description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniamquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
   image: "assets/images/icona_degrado_urbano.png",
   image1: "assets/images/panchina.jpg",
   image2: "assets/images/icona_noPhoto.png",
   mappa:"assets/images/mappaPordenone.png",
    indirizzo:"Via Prasecco, 3/a Pordenone",
  ),
  Segnalazione(
    id: "5",
    titolo: "Titolo Segnalazione",
    data: "02/02/2020",
    stato: "Risolto",
    sostegno: 4 ,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniamquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: "assets/images/icona_illuminazione.png",
    image1: "assets/images/icona_noPhoto.png",
    image2: "assets/images/icona_noPhoto.png",
    mappa:"assets/images/mappaPordenone.png",
    indirizzo:"Via Prasecco, 3/a Pordenone",
  ),
  Segnalazione(
    id: "6",
    titolo: "Titolo Segnalazione",
    data: "01/02/2020",
    stato: "Risolto",
    sostegno: 2 ,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniamquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image2: "assets/images/icona_noPhoto.png",
    image1: "assets/images/icona_noPhoto.png",
    image: "assets/images/icona_cartelli_stradali.png",
    mappa:"assets/images/mappaPordenone.png",
    indirizzo:"Via Prasecco, 3/a Pordenone",
  ),
  Segnalazione(
      id: "7",
      titolo: "Titolo Segnalazione",
      data: "01/02/2020",
      stato: "Negato",
      sostegno: 0 ,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniamquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      image: "assets/images/icona_vandalismo.png",
      image2: "assets/images/icona_noPhoto.png",
      image1: "assets/images/icona_noPhoto.png",
      mappa:"assets/images/mappaPordenone.png",
      indirizzo:"Via Prasecco, 3/a Pordenone"
  ),
  Segnalazione(
    id: "8",
    titolo: "Titolo Segnalazione",
    data: "29/01/2020",
    stato: "Risolto",
    sostegno: 3 ,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniamquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: "assets/images/icona_verde.png",
    image2: "assets/images/icona_noPhoto.png",
    image1: "assets/images/icona_noPhoto.png",
    mappa:"assets/images/mappaPordenone.png",
    indirizzo:"Via Prasecco, 3/a Pordenone",
  ),
  Segnalazione(
    id: "9",
    titolo: "Titolo Segnalazione",
    data: "27/01/2020",
    stato: "Attesa",
    sostegno: 2 ,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniamquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: "assets/images/icona_dissesto.png",
    image2: "assets/images/icona_noPhoto.png",
    image1: "assets/images/dissesto.jpg",
    mappa:"assets/images/mappaPordenone.png",
    indirizzo:"Via Prasecco, 3/a Pordenone",
  ),
  Segnalazione(
    id: "10",
    titolo: "Titolo Segnalazione",
    data: "24/01/2020",
    stato: "Negato",
    sostegno: 0 ,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniamquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: "assets/images/icona_altro.png",
    image2: "assets/images/icona_noPhoto.png",
    image1: "assets/images/icona_noPhoto.png",
    mappa:"assets/images/mappaPordenone.png",
    indirizzo:"Via Prasecco, 3/a Pordenone",
  ),
  Segnalazione(
    id: "11",
    titolo: "Titolo Segnalazione",
    data: "20/01/2020",
    stato: "Risolto",
    sostegno: 2 ,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniamquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: "assets/images/icona_animale_vagante.png",
    image2: "assets/images/icona_noPhoto.png",
    image1: "assets/images/icona_noPhoto.png",
    mappa:"assets/images/mappaPordenone.png",
    indirizzo:"Via Prasecco, 3/a Pordenone",
  ),
  Segnalazione(
    id: "12",
    titolo: "Titolo Segnalazione",
    data: "16/01/2020",
    stato: "Attesa",
    sostegno: 7 ,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniamquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: "assets/images/icona_spazzatura.png",
    image2: "assets/images/icona_noPhoto.png",
    image1: "assets/images/icona_noPhoto.png",
    mappa:"assets/images/mappaPordenone.png",
    indirizzo:"Via Prasecco, 3/a Pordenone",
  ),
  Segnalazione(
    id: "13",
    titolo: "Titolo Segnalazione",
    data: "16/01/2020",
    stato: "Risolto",
    sostegno: 9 ,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniamquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: "assets/images/icona_spazzatura.png",
    image2: "assets/images/icona_noPhoto.png",
    image1: "assets/images/icona_noPhoto.png",
    mappa:"assets/images/mappaPordenone.png",
    indirizzo:"Via Prasecco, 3/a Pordenone",
  ),
  Segnalazione(
    id: "14",
    titolo: "Titolo Segnalazione",
    data: "14/01/2020",
    stato: "Risolto",
    sostegno: 0 ,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniamquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: "assets/images/icona_animale_vagante.png",
    image2: "assets/images/icona_noPhoto.png",
    image1: "assets/images/icona_noPhoto.png",
    mappa:"assets/images/mappaPordenone.png",
    indirizzo:"Via Prasecco, 3/a Pordenone",
  ),
  Segnalazione(
    id: "15",
    titolo: "Titolo Segnalazione",
    data: "11/01/2020",
    stato: "Risolto",
    sostegno: 6 ,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniamquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: "assets/images/icona_spazzatura.png",
    image2: "assets/images/icona_noPhoto.png",
    image1: "assets/images/icona_noPhoto.png",
    mappa:"assets/images/mappaPordenone.png",
    indirizzo:"Via Prasecco, 3/a Pordenone",
  ),
  Segnalazione(
    id: "16",
    titolo: "Titolo Segnalazione",
    data: "09/01/2020",
    stato: "Risolto",
    sostegno: 1 ,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniamquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: "assets/images/icona_animale_vagante.png",
    image2: "assets/images/icona_noPhoto.png",
    image1: "assets/images/icona_noPhoto.png",
    mappa:"assets/images/mappaPordenone.png",
    indirizzo:"Via Prasecco, 3/a Pordenone",
  ),
  Segnalazione(
      id: "17",
      titolo: "Titolo Segnalazione",
      data: "07/01/2020",
      stato: "Negato",
      sostegno: 2 ,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniamquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      image: "assets/images/icona_illuminazione.png",
      image2: "assets/images/icona_noPhoto.png",
      image1: "assets/images/icona_noPhoto.png",
      mappa:"assets/images/mappaPordenone.png",
      indirizzo:"Via Prasecco, 3/a Pordenone"
  ),
  Segnalazione(
    id: "18",
    titolo: "Titolo Segnalazione",
    data: "02/01/2020",
    stato: "Risolto",
    sostegno: 5 ,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniamquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: "assets/images/icona_degrado_urbano.png",
    image2: "assets/images/icona_noPhoto.png",
    image1: "assets/images/icona_noPhoto.png",
    mappa:"assets/images/mappaPordenone.png",
    indirizzo:"Via Prasecco, 3/a Pordenone",
  ),
  Segnalazione(
    id: "19",
    titolo: "Titolo Segnalazione",
    data: "02/01/2020",
    stato: "Risolto",
    sostegno: 3 ,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniamquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: "assets/images/icona_animale_vagante.png",
    image2: "assets/images/icona_noPhoto.png",
    image1: "assets/images/icona_noPhoto.png",
    mappa:"assets/images/mappaPordenone.png",
    indirizzo:"Via Prasecco, 3/a Pordenone",
  ),
];