name: bottomnavbar
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.3+1
  carousel_slider: ^1.3.0
  google_fonts: ^0.3.5
  intro_views_flutter: ^2.8.0
  grouped_buttons: ^1.0.4
  shared_preferences: ^0.4.3
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  image_path: "assets/images/icona_launcher.png"
  android: true




dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:



  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/images/iconaApp.png
    - assets/images/icona_animale_vagante.png
    - assets/images/icona_animali_selvaggi.png
    - assets/images/icona_altro.png
    - assets/images/icona_cartelli_stradali.png
    - assets/images/icona_dissesto.png
    - assets/images/icona_degrado_urbano.png
    - assets/images/icona_verde.png
    - assets/images/icona_vandalismo.png
    - assets/images/icona_illuminazione.png
    - assets/images/icona_spazzatura.png
    - assets/images/mappaPordenone.png
    - assets/images/iconaApp.jpg
    - assets/images/podio1.png
    - assets/images/podio2.png
    - assets/images/podio3.png
    - assets/images/podio4.png
    - assets/images/podio5.png
    - assets/images/podio6.png
    - assets/images/podio7.png
    - assets/images/podio8.png
    - assets/images/podio9.png
    - assets/images/podio10.png
    - assets/images/icona_addPhoto.png
    - assets/images/icona_noPhoto.png
    - assets/images/logo-scritta.png
    - assets/images/icona_segnalazioni_tutorial.png
    - assets/images/icona_tutorial.png
    - assets/images/icona_comunicazioni_tutorial.png
    - assets/images/icon_google.png
    - assets/images/icon_facebook.png
    - assets/images/cane.jpg
    - assets/images/spazzatura.jpg
    - assets/images/panchina.jpg
    - assets/images/lepre.jpg
    - assets/images/dissesto.jpg
